compiler:
  solc:
    version: 0.8.6
    optimizer:
      enabled: true
      runs: 200
    remappings:
    - "@openzeppelin=node_modules/@openzeppelin"
    - "@aave=node_modules/@aave"
    - "@uniswap=node_modules/@uniswap"
