compiler:
  solc:
    version: 0.8.16
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=node_modules/@openzeppelin"
      - "hardhat=node_modules/hardhat"
networks:
  default: hardhat
