version: "3.4"

services:
  devenv:
    command: ["sh", "-c", "while [ 0 ]; do date; sleep 30 ; done"]
    build:
      args:
        DEV_ENV: "1"
        # BASE_CONTAINER: "minimal-notebook-pypy:latest"
    volumes:
      - ./:/usr/local/app/
