version: "3.4"

services:
  devenv:
    command: ["sh", "-c", "while [ 0 ]; do date; sleep 30 ; done"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ensuro_devenv
    env_file: .env
