x-podman:
  in_pod: false

services:
  devenv:
    command: ["sh", "-c", "while [ 0 ]; do date; sleep 30 ; done"]
    userns_mode: keep-id
    build:
      args:
        DEV_ENV: "1"
        # BASE_CONTAINER: "minimal-notebook-pypy:latest"
    volumes:
      - ./:/home/ensuro/code
