[tool.black]
line-length = 110

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

filterwarnings = [
    # Disable MismatchedABI warnings for event parsing, they're not relevant for our tests
    'ignore:.*MismatchedABI\(The event signature did not match the provided ABI\).*',
    'ignore:.*LogTopicError\(.*\). It has been discarded\..*',
]
