version: "3.4"

services:
  server:
    command: ["sh", "-c", "while [ 0 ]; do date; sleep 30 ; done"]
    build:
      args:
        DEV_ENV: "1"
    ports:
      - ${FLASK_EXT_PORT:-5000}:5000
      - ${JUPYTER_EXT_PORT:-8888}:8888
    volumes:
      - ./:/home/jovyan/app/
      - ./notebooks/:/home/jovyan/work/
