name: Ensuro SmartContract Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    container:
      image: gnarvaja/eth-dev:ensuro-1.0.4
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - run: SKIP_PROXY=1 brownie test -v --coverage
        timeout-minutes: 40
      - run: ./instrumented-tests.sh
