name: Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup
        run: |
          npm ci
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - name: Run python tests
        run: |
          . scripts/utils.sh
          startHHNode

          pytest

          killPID $(getHHNodePID) || true
      - run: scripts/deploySmokeTest.sh
      - run: scripts/deploySmokeTest-fork.sh
        env:
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      - run: npx hardhat test
        env:
          REPORT_GAS: "1"
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}

  coverage:
    name: Full coverage measurement
    runs-on: ubuntu-latest
    timeout-minutes: 45

    # Grant permissions for the coverage-action to push on the coverage branch and write on the pull request
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup
        run: |
          npm ci
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - run: npx hardhat python-coverage

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          # Path to the Cobertura XML report.
          path: ./coverage/cobertura-coverage.xml
          # Fail the workflow if the minimum code coverage
          # reuqirements are not satisfied.
          fail: true
          # Publish the rendered output as a PR comment
          publish: true
          # Create a coverage diff report.
          diff: true
          # Branch to diff against.
          # Compare the current coverage to the coverage
          # determined on this branch.
          diff-branch: main
          # This is where the coverage reports for the
          # `diff-branch` are stored.
          # Branch is created if it doesn't already exist'.
          diff-storage: _xml_coverage_reports
