name: Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - name: Run python tests
        run: |
          npx hardhat node > /dev/null &
          NODE_PID=$!
          scripts/wait-node.sh http://localhost:8545
          pytest
          kill $NODE_PID
          wait $NODE_PID
      - run: scripts/deploySmokeTest.sh
      - run: scripts/deploySmokeTest-fork.sh
        env:
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      - run: npx hardhat test
        env:
          REPORT_GAS: "1"
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      - run: npx hardhat python-coverage
      - name: Create coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          set -x
          COVERAGE_BADGE=badges/coverage.svg
          mkdir -p badges
          npx lcov-badge2 -o $COVERAGE_BADGE coverage/lcov.info
          git config --global user.name 'Tests workflow'
          git config --global user.email 'ensuro@users.noreply.github.com'

          git add $COVERAGE_BADGE
          if ! git diff HEAD -s --exit-code $COVERAGE_BADGE; then
            git commit -m "Add coverage badge" $COVERAGE_BADGE && \
            git push;
          fi
