name: Ensuro SmartContract Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    container:
      image: gnarvaja/eth-dev
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - run: SKIP_PROXY=1 brownie test -v --coverage
        timeout-minutes: 30
      - run: ./instrumented-tests.sh
      - run: SKIP_PROXY=1 brownie test --network polygon-main-fork -s -k test_aave_assetmanager
