name: Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - run: brownie test -v --gas
      - run: scripts/deploySmokeTest.sh
      - run: scripts/deploySmokeTest-fork.sh
        env:
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      - run: npx hardhat test
        env:
          ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      - run: node instrumented/coverage.js
      - name: Create coverage badge
        run: |
          COVERAGE_BADGE=badges/coverage.svg
          mkdir -p badges
          npx lcov-badge2 -o $COVERAGE_BADGE coverage/lcov.info
          git config --global user.name 'Tests workflow'
          git config --global user.email 'ensuro@users.noreply.github.com'

          git diff -s --exit-code $COVERAGE_BADGE || {
            git add $COVERAGE_BADGE && \
              git commit -m "Add coverage badge" $COVERAGE_BADGE && \
              git push;
          }
