name: Ensuro SmartContract Tests
on: [push]

jobs:
  tests:
    name: Ensuro Tests
    runs-on: ubuntu-latest
    container:
      image: gnarvaja/eth-dev
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - run: ./ci-tests.sh
        timeout-minutes: 20
